from enum import Enum
from typing import Dict, List


class Intent(str, Enum):
    COURSE_REGISTRATION = "course_registration"
    ADMISSION = "admission"
    EXAM_SCHEDULE = "exam_schedule"
    ACADEMIC_CALENDAR = "academic_calendar"
    RESULTS = "results"
    PORTAL_PROBLEM = "portal_problem"
    PASSWORD_CHANGE = "password_change"
    PERSONAL_DETAILS = "personal_details"
    DEPARTMENTAL_ISSUE = "departmental_issue"
    FEES = "fees"
    GENERAL_INFORMATION = "general_information"
    HUMAN_SUPPORT = "human_support"
    UNKNOWN = "unknown"


INTENT_KEYWORDS: Dict[Intent, List[str]] = {
    Intent.COURSE_REGISTRATION: [
        "course registration",
        "register courses",
        "how to register",
        "registration close",
        "registration deadline",
        "add course",
        "drop course",
        "change course",
        "course selection",
        "class registration",
        "semester registration",
        "register for modules",
        "register subjects",
        "course enrolment",
        "course enrollment",
    ],
    Intent.ADMISSION: [
        "admission",
        "admissions",
        "apply",
        "application",
        "how to apply",
        "apply for admission",
        "entry requirements",
        "prospectus",
        "registration for new students",
        "intake",
        "admission date",
        "acceptance letter",
        "application status",
        "admission requirements",
    ],
    Intent.EXAM_SCHEDULE: [
        "exam schedule",
        "examination timetable",
        "exam timetable",
        "when is exam",
        "exam date",
        "midterm schedule",
        "final exam",
        "examination dates",
        "exam paper",
        "supplementary exam",
        "re-sit exam",
        "resit exam",
        "assessment schedule",
    ],
    Intent.ACADEMIC_CALENDAR: [
        "academic calendar",
        "school calendar",
        "university calendar",
        "semester dates",
        "semester starts",
        "semester ends",
        "holiday dates",
        "recess week",
        "reading week",
        "study break",
        "university closure",
        "important dates",
        "registration period",
        "holiday schedule",
    ],
    Intent.RESULTS: [
        "results",
        "exam results",
        "grades",
        "marks",
        "score",
        "my result",
        "how to check result",
        "result release",
        "transcript",
        "academic record",
        "grade point",
        "gpa",
        "cgpa",
        "supplementary result",
    ],
    Intent.PORTAL_PROBLEM: [
        "portal problem",
        "portal not working",
        "can't access portal",
        "cannot login portal",
        "portal error",
        "student portal",
        "school portal",
        "portal down",
        "website not working",
        "my portal removed",
        "portal courses missing",
        "portal issue",
        "can't log into portal",
        "portal login issue",
    ],
    Intent.PASSWORD_CHANGE: [
        "forgot password",
        "reset password",
        "change password",
        "password recovery",
        "password reset",
        "forgot my password",
        "recover password",
        "update password",
        "my password doesn't work",
        "locked out",
        "cannot login",
        "password expired",
        "unlock account",
    ],
    Intent.PERSONAL_DETAILS: [
        "personal details",
        "personal information",
        "update phone number",
        "change address",
        "update contact",
        "change phone",
        "update email",
        "change my profile",
        "profile update",
        "edit my details",
        "address change",
        "next of kin",
        "contact information",
        "emergency contact",
    ],
    Intent.DEPARTMENTAL_ISSUE: [
        "departmental issue",
        "department problem",
        "my department",
        "contact department",
        "department support",
        "lecturer issue",
        "faculty problem",
        "course coordinator",
        "department head",
        "hod",
        "faculty issue",
        "school department",
        "csc department",
        "my faculty",
    ],
    Intent.FEES: [
        "fees",
        "tuition fees",
        "school fees",
        "payment",
        "fee payment",
        "how to pay fees",
        "fee deadline",
        "fee structure",
        "amount to pay",
        "outstanding fees",
        "late payment",
        "billing",
        "invoice",
        "financial aid",
    ],
    Intent.GENERAL_INFORMATION: [
        "general information",
        "about the university",
        "where is",
        "how do i",
        "student handbook",
        "university policy",
        "rules and regulations",
        "contact university",
        "general enquiry",
        "frequently asked",
        "library hours",
        "facility",
        "campus information",
    ],
    Intent.HUMAN_SUPPORT: [
        "talk to a person",
        "speak to human",
        "human support",
        "i need a staff",
        "contact support",
        "escalate",
        "speak to someone",
        "customer service",
        "technical support",
        "need help from staff",
        "i want to create a ticket",
        "staff assistance",
        "help desk",
        "not helping",
        "this is not helpful",
    ],
    Intent.UNKNOWN: [],
}


INTENT_TO_CATEGORY: Dict[Intent, str] = {
    Intent.COURSE_REGISTRATION: "registration",
    Intent.ADMISSION: "admission",
    Intent.EXAM_SCHEDULE: "examination",
    Intent.ACADEMIC_CALENDAR: "academic_calendar",
    Intent.RESULTS: "results",
    Intent.PORTAL_PROBLEM: "portal",
    Intent.PASSWORD_CHANGE: "password",
    Intent.PERSONAL_DETAILS: "general",
    Intent.DEPARTMENTAL_ISSUE: "departments",
    Intent.FEES: "fees",
    Intent.GENERAL_INFORMATION: "general",
    Intent.HUMAN_SUPPORT: "general",
    Intent.UNKNOWN: "general",
}


INTENT_DESCRIPTIONS: Dict[Intent, str] = {
    Intent.COURSE_REGISTRATION: "Queries about course registration, adding or dropping modules, and enrolment deadlines.",
    Intent.ADMISSION: "Queries about admissions, application processes, and entry requirements.",
    Intent.EXAM_SCHEDULE: "Queries about examination schedules, timetables, and assessment dates.",
    Intent.ACADEMIC_CALENDAR: "Queries about the academic calendar, semester dates, holidays, and important periods.",
    Intent.RESULTS: "Queries about exam results, grades, transcripts, GPA, and academic records.",
    Intent.PORTAL_PROBLEM: "Issues with accessing or using the student portal.",
    Intent.PASSWORD_CHANGE: "Password recovery, reset, and account lockout assistance.",
    Intent.PERSONAL_DETAILS: "Updating personal information, contact details, and profile data.",
    Intent.DEPARTMENTAL_ISSUE: "Issues or enquiries related to a specific department or faculty.",
    Intent.FEES: "Queries about tuition fees, payment methods, deadlines, and billing.",
    Intent.GENERAL_INFORMATION: "General university information, policies, and directions.",
    Intent.HUMAN_SUPPORT: "User explicitly requests to speak to a human staff member.",
    Intent.UNKNOWN: "Intent could not be determined with sufficient confidence.",
}

INTENTS: List[str] = [i.value for i in Intent]
